[package]
name = "mi_lon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.5", features = ["derive"] }
crossterm = { version = "0.22.1"}
ropey = {version = "1.3.2"}